### ISSUE TITLE
View is not like preview

### ISSUE THREAD

**Issue by SW1605** [NoFear23m/TileGridGenerator#1]
In the preview, the photos are inserted in 3 columns, after copying the code in the homepage, the pictures are below each other instead of side by side.

Anwendung: NopCommerce Shop 4.1

![Preview](https://user-images.githubusercontent.com/31240330/66981746-ea77a580-f0b4-11e9-8eb4-290a5ed86d18.GIF)
![View](https://user-images.githubusercontent.com/31240330/66981747-eb103c00-f0b4-11e9-9ad9-10e4718da509.GIF)

**Comment by NoFear23m** [comment]
Thanks, can you post me a link to the resulted page. I try to analyse the problem. Thanks

**Comment by SW1605** [comment]
https://www.birdys-leinentraum.at/galerie

**Comment by SW1605** [comment]
https://www.birdys-leinentraum.at/galerie

**Comment by NoFear23m** [comment]
On that page there are missing the css. See Screenshot. Only the HTML exist.
I will try it on the Adminarea and give you response
![Anmerkung 2019-10-17 084132](https://user-images.githubusercontent.com/15660141/66984018-2d884780-f0ba-11e9-84cd-ef9d121cc765.png)
 soon as possible.

**Comment by NoFear23m** [comment]
Hello 

The sourcecodeeditor in NopCommerce cuts the Styles out. you must set a special editor-setting. See Screenshot. Now the styles are running. But another problem with stretching the background is there now, but you can now test it a while and i will see to fix that small issue.

![Anmerkung 2019-10-17 090800](https://user-images.githubusercontent.com/15660141/66985874-02075c00-f0be-11e9-9784-4bf15b67123c.png)
