### ISSUE TITLE
Front color (Registration bar)

### ISSUE THREAD

**Issue by SW1605** [NoFear23m/TileGridGenerator#2]
The color of the lettering in the registration bar is white on the side of the gallery but gray on the other pages.

Application: Nop Commerce Shop 4.1
![Galerie](https://user-images.githubusercontent.com/31240330/66989260-4d246d80-f0c4-11e9-9756-86fcc0da682e.GIF)
![Andere Seite](https://user-images.githubusercontent.com/31240330/66989261-4d246d80-f0c4-11e9-80e1-8cedc2e32fdd.GIF)

**Comment by NoFear23m** [comment]
I think i have fixed that Issue. Please test the latest beta-release: https://github.com/NoFear23m/TileGridGenerator/releases/tag/v1.1-beta
